/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the projects of the caller
         * @description Newest first, a page at a time.
         */
        get: operations["projects.list"];
        put?: never;
        /** Create a project */
        post: operations["projects.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["projects.get"];
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description A project with tasks can't be deleted: delete its tasks first.
         */
        delete: operations["projects.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tasks of a project
         * @description Newest first, a page at a time, of a status or of any.
         */
        get: operations["tasks.list"];
        put?: never;
        /**
         * Create a task in a project
         * @description The task gets the next number of its project: 1, 2, and so on.
         */
        post: operations["tasks.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task */
        get: operations["tasks.get"];
        put?: never;
        post?: never;
        /** Delete a task */
        delete: operations["tasks.delete"];
        options?: never;
        head?: never;
        /**
         * Change a task
         * @description The fields of the request change those of the task, and the fields it leaves out keep their values.
         */
        patch: operations["tasks.update"];
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count the projects and tasks of all owners */
        get: operations["admin.stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Page_Project: {
            /** @description The items of the page, newest first. */
            items: components["schemas"]["Project"][];
            /** @description The cursor of the next page; none after the last page. */
            next_cursor?: string;
        };
        Page_Task: {
            /** @description The items of the page, newest first. */
            items: components["schemas"]["Task"][];
            /** @description The cursor of the next page; none after the last page. */
            next_cursor?: string;
        };
        Problem: {
            /**
             * Format: uri-reference
             * @description The URI reference of the problem type: one per kind, or about:blank for a problem of the HTTP request itself.
             */
            type: string;
            /** @description The title of the problem type. */
            title: string;
            /** @description The HTTP status. */
            status: number;
            /** @description The message of the error. */
            detail?: string;
            /**
             * @description The kind of the error. A problem of the HTTP request itself has none.
             * @enum {string}
             */
            kind?: "internal" | "invalid_argument" | "unauthenticated" | "permission_denied" | "not_found" | "already_exists" | "failed_precondition" | "resource_exhausted" | "deadline_exceeded" | "unavailable" | "canceled";
            /** @description The fields that failed validation, with invalid_argument. */
            errors?: components["schemas"]["Violation"][];
            /** @description The details of an error of another kind. */
            details?: unknown;
        };
        Project: {
            /**
             * Format: uuid
             * @description The id of the project.
             */
            id: string;
            /** @description A short code of the project, unique among the projects of its owner, such as WEB. */
            key: string;
            /** @description The name of the project. */
            name: string;
            /**
             * Format: date-time
             * @description When the project was created.
             */
            created_at: string;
        };
        ProjectCreated: {
            /**
             * Format: uuid
             * @description The id of the project.
             */
            id: string;
            /** @description A short code of the project, unique among the projects of its owner, such as WEB. */
            key: string;
            /** @description The name of the project. */
            name: string;
            /**
             * Format: date-time
             * @description When the project was created.
             */
            created_at: string;
        };
        Stats: {
            /** @description The number of projects. */
            projects: number;
            /** @description The number of tasks. */
            tasks: number;
            /** @description The number of tasks done. */
            done: number;
        };
        Task: {
            /**
             * Format: uuid
             * @description The id of the task.
             */
            id: string;
            /**
             * Format: uuid
             * @description The id of the project of the task.
             */
            project_id: string;
            /** @description The number of the task within its project: 1 for the first one. */
            number: number;
            /** @description What to do. */
            title: string;
            /** @description todo, doing or done. */
            status: string;
            /**
             * Format: date-time
             * @description When the task is due, if it is.
             */
            due_at?: string;
            /**
             * Format: date-time
             * @description When the task was created.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the task last changed.
             */
            updated_at: string;
        };
        TaskCreated: {
            /**
             * Format: uuid
             * @description The id of the task.
             */
            id: string;
            /**
             * Format: uuid
             * @description The id of the project of the task.
             */
            project_id: string;
            /** @description The number of the task within its project: 1 for the first one. */
            number: number;
            /** @description What to do. */
            title: string;
            /** @description todo, doing or done. */
            status: string;
            /**
             * Format: date-time
             * @description When the task is due, if it is.
             */
            due_at?: string;
            /**
             * Format: date-time
             * @description When the task was created.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the task last changed.
             */
            updated_at: string;
        };
        Violation: {
            /** @description A JSON Pointer to the field in the JSON form of the request, such as /code. */
            pointer: string;
            /** @description What's wrong with the field. */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "projects.list": {
        parameters: {
            query?: {
                /** @description How many projects to return: 20 if not set. */
                limit?: number;
                /** @description The next_cursor of the page before, for the page after it. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Project"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "projects.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A short code of the project, of A-Z and 0-9, starting with a letter, such as WEB. The projects of a caller have keys of their own. */
                    key: string;
                    /** @description The name of the project. */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description The path of the project. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreated"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Already Exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/already_exists";
                        /** @constant */
                        kind: "already_exists";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "projects.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "projects.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Failed Precondition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/failed_precondition";
                        /** @constant */
                        kind: "failed_precondition";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "tasks.list": {
        parameters: {
            query?: {
                /** @description Only the tasks of the status, if set: todo, doing or done. */
                status?: "todo" | "doing" | "done";
                /** @description How many tasks to return: 20 if not set. */
                limit?: number;
                /** @description The next_cursor of the page before, for the page after it. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description The id of the project. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Task"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "tasks.create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the project. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description What to do. */
                    title: string;
                    /**
                     * @description todo, doing or done: todo if not set.
                     * @enum {string}
                     */
                    status?: "todo" | "doing" | "done";
                    /**
                     * Format: date-time
                     * @description When the task is due.
                     */
                    due_at?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description The path of the task. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "tasks.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the task. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "tasks.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the task. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "tasks.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the task. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description What to do. */
                    title?: string | null;
                    /**
                     * @description todo, doing or done.
                     * @enum {string|null}
                     */
                    status?: "todo" | "doing" | "done" | null;
                    /**
                     * Format: date-time
                     * @description When the task is due.
                     */
                    due_at?: string | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/not_found";
                        /** @constant */
                        kind: "not_found";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "admin.stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            /** @description Invalid Argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/invalid_argument";
                        /** @constant */
                        kind: "invalid_argument";
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    /** @description A challenge per scheme that the server accepts. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unauthenticated";
                        /** @constant */
                        kind: "unauthenticated";
                    };
                };
            };
            /** @description Permission Denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/permission_denied";
                        /** @constant */
                        kind: "permission_denied";
                    };
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/unavailable";
                        /** @constant */
                        kind: "unavailable";
                    };
                };
            };
            /** @description Deadline Exceeded */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"] & {
                        /** @constant */
                        type: "/problems/deadline_exceeded";
                        /** @constant */
                        kind: "deadline_exceeded";
                    };
                };
            };
            /** @description An error of another kind, or a problem of the HTTP request itself. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
