// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"uuid"
)

type Project struct {
	ID         uuid.UUID
	OwnerID    string
	Key        string
	Name       string
	LastNumber int32
	CreatedAt  time.Time
}

type Task struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Number    int32
	Title     string
	Status    string
	DueAt     *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
