// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"

	"uuid"
)

const countAll = `-- name: CountAll :one
SELECT
    (SELECT count(*) FROM projects) AS projects,
    (SELECT count(*) FROM tasks) AS tasks,
    (SELECT count(*) FROM tasks WHERE status = 'done') AS done
`

type CountAllRow struct {
	Projects int64
	Tasks    int64
	Done     int64
}

// The number of projects and tasks, and of the tasks done, of all owners.
func (q *Queries) CountAll(ctx context.Context) (CountAllRow, error) {
	row := q.db.QueryRow(ctx, countAll)
	var i CountAllRow
	err := row.Scan(&i.Projects, &i.Tasks, &i.Done)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, owner_id, key, name)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, key, name, last_number, created_at
`

type CreateProjectParams struct {
	ID      uuid.UUID
	OwnerID string
	Key     string
	Name    string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OwnerID,
		arg.Key,
		arg.Name,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Name,
		&i.LastNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = $1 AND owner_id = $2
`

type DeleteProjectParams struct {
	ID      uuid.UUID
	OwnerID string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, key, name, last_number, created_at FROM projects
WHERE id = $1 AND owner_id = $2
`

type GetProjectParams struct {
	ID      uuid.UUID
	OwnerID string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Name,
		&i.LastNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, owner_id, key, name, last_number, created_at FROM projects
WHERE owner_id = $1
  AND ($2::uuid IS NULL OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListProjectsParams struct {
	OwnerID string
	After   *uuid.UUID
	Max     int32
}

// The projects of an owner, newest first, after the project after if it
// isn't null.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.OwnerID, arg.After, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Key,
			&i.Name,
			&i.LastNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTaskNumber = `-- name: NextTaskNumber :one
UPDATE projects
SET last_number = last_number + 1
WHERE id = $1 AND owner_id = $2
RETURNING last_number
`

type NextTaskNumberParams struct {
	ID      uuid.UUID
	OwnerID string
}

// Numbers a new task of a project. The update locks the row of the
// project until the transaction ends, so that tasks created at once get
// numbers one after another.
func (q *Queries) NextTaskNumber(ctx context.Context, arg NextTaskNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextTaskNumber, arg.ID, arg.OwnerID)
	var last_number int32
	err := row.Scan(&last_number)
	return last_number, err
}
