// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, project_id, number, title, status, due_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, number, title, status, due_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Number    int32
	Title     string
	Status    string
	DueAt     *time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.ProjectID,
		arg.Number,
		arg.Title,
		arg.Status,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
USING projects
WHERE tasks.id = $1
  AND projects.id = tasks.project_id
  AND projects.owner_id = $2
`

type DeleteTaskParams struct {
	ID      uuid.UUID
	OwnerID string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT tasks.id, tasks.project_id, tasks.number, tasks.title, tasks.status, tasks.due_at, tasks.created_at, tasks.updated_at FROM tasks
JOIN projects ON projects.id = tasks.project_id
WHERE tasks.id = $1 AND projects.owner_id = $2
`

type GetTaskParams struct {
	ID      uuid.UUID
	OwnerID string
}

// A task of a project of the owner.
func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OwnerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, project_id, number, title, status, due_at, created_at, updated_at FROM tasks
WHERE project_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListTasksParams struct {
	ProjectID uuid.UUID
	Status    *string
	After     *uuid.UUID
	Max       int32
}

// The tasks of a project, newest first, of the status if it isn't null,
// after the task after if it isn't null. The project must be the owner's:
// check it first.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.ProjectID,
		arg.Status,
		arg.After,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = coalesce($1, tasks.title),
    status = coalesce($2, tasks.status),
    due_at = coalesce($3, tasks.due_at),
    updated_at = now()
FROM projects
WHERE tasks.id = $4
  AND projects.id = tasks.project_id
  AND projects.owner_id = $5
RETURNING tasks.id, tasks.project_id, tasks.number, tasks.title, tasks.status, tasks.due_at, tasks.created_at, tasks.updated_at
`

type UpdateTaskParams struct {
	Title   *string
	Status  *string
	DueAt   *time.Time
	ID      uuid.UUID
	OwnerID string
}

// Sets the fields that aren't null, of a task of a project of the owner.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Status,
		arg.DueAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
